//
//  DisplayRequestType.swift
//  ePOS
//
//  Created by Vishal Rathore on 11/12/20.
//  Copyright © 2020 Pinelabs. All rights reserved.
//

import Foundation

enum DisplayRequestType
{
    static let REQUEST_FOR_EMV_ONLINE_PIN = 95
    static let RESPONSE_FOR_EMV_ONLINE_PIN = 96
    static let GETTING_ADDITIONAL_INFO = 97
    static let ADDITIONAL_INFO_OBTAINED = 98
    static let FALL_BACK = 99
    static let REQUEST_SIGNATURE_CAPTURE = 2001
    static let REQUEST_FOR_APP_SELECTION_ACTIVITY = 1001
    static let RESPONSE_FOR_APP_SELECTION_ACTIVITY = 1002
    static let REQUEST_FOR_SHOW_DIALOG = 180
    static let REQUEST_FOR_SHOW_TOAST = 19

    static let  REQUEST_FOR_CDISPLAYMENU_ACTIVITY = 0
    static let  RESPONSE_FOR_CDISPLAYMENU_ACTIVITY = 1
    static let  REQUEST_FOR_CDISPLAYWAIT_ACTIVITY = 2
    static let  RESPONSE_FOR_CDISPLAYWAIT_ACTIVITY = 3
    static let  REQUEST_FOR_CDISPLAYEVENTRECEIVED_ACTIVITY = 4
    static let  RESPONSE_FOR_CDISPLAYEVENTRECEIVED_ACTIVITY = 5
    static let  REQUEST_FOR_PIN_AFTER_EVENT_RECEIVED = 41
    static let  RESPONSE_FOR_PIN_AFTER_EVENT_RECEIVED = 42
    static let  REQUEST_FOR_ACCOUNT_SELECTION_ACTIVITY = 43
    static let  RESPONSE_FOR_ACCOUNT_SELECTION_ACTIVITY = 43
    static let  REQUEST_FOR_CDISPLAYGETAMOUNT_ACTIVITY = 6
    static let  RESPONSE_FOR_CDISPLAYGETAMOUNT_ACTIVITY = 7
    static let  REQUEST_FOR_CDISPLAYGETSECRETPIN_ACTIVITY = 8
    static let  RESPONSE_FOR_CDISPLAYGETSECRETPIN_ACTIVITY = 9
    static let  REQUEST_FOR_CDISPLAYMESSAGE_ACTIVITY = 10
    static let  RESPONSE_FOR_CDISPLAYMESSAGE_ACTIVITY = 11
    static let  REQUEST_FOR_CDISPLAY_CONFIRMATION_ACTIVITY = 12
    static let  RESPONSE_FOR_CDISPLAY_CONFIRMATION_ACTIVITY = 13
    static let  REQUEST_FOR_CDISPLAY_DATA_ENTRY_ACTIVITY = 14
    static let  RESPONSE_FOR_CDISPLAY_DATA_ENTRY_ACTIVITY = 15
    static let  REQUEST_FOR_CDISPLAYMENULIST_ACTIVITY = 16
    static let  RESPONSE_FOR_CDISPLAYMENULIST_ACTIVITY = 17
    static let  RESPONSE_FOR_TOUCH_EVENT_ON_WAITFOREVENT_ACTIVITY = 18
    static let  REQUEST_FOR_PRINT_SLIP = 20
    //public static final int REQUEST_FOR_SETTLEMENT_SLIP = 201
    static let  REQUEST_FOR_WAITFOREVENT_ACTIVITY = 21
    static let  RESPONSE_FOR_WAITFOREVENT_ACTIVITY = 22
    static let  REQUEST_FOR_QR_CODE_ACTIVITY = 23
    static let  RESPONSE_FOR_QR_CODE_ACTIVITY = 24
    static let  REQUEST_FOR_SIGNATURE_CAPTURE = 25

    static let REQUEST_FOR_QRCODE_SCANNING_ACTIVITY = 25
    static let RESPONSE_FOR_QRCODE_SCANNING_ACTIVITY = 26

    /*    public static final int REQUEST_FOR_MERCHANT_LOGIN_ACTIVITY = 27;
        public static final int RESPONSE_FOR_MERCHANT_LOGIN_ACTIVITY = 28;*/

    static let FINISH_TRANSACTION_HUB_ACTIVITY = 30

    static let REQUEST_FOR_OFFLINE_PIN_ENTRY = 31
    static let RESPONSE_FOR_OFFLINE_PIN_ENTRY = 31

    //public static final int REQUEST_FOR_SERIAL_LISTENER = 31
    static let REQUEST_TO_GO_ONLINE_CSV_TXN_NORMAL = 32
    static let REQUEST_TO_GO_ONLINE_CSV_TXN_SWIPE = 33
    static let REQUEST_TO_GO_ONLINE_CSV_TXN_EMV_CLESS = 34

    static let REQUEST_TO_GO_ONLINE = 35

    static let REQUEST_FOR_GIF_VIDEO_ACTIVITY = 36
    static let RESPONSE_FOR_GIF_VIDEO_ACTIVITY = 37
    static let RESPONSE_FROM_PRINT_SLIP = 38

    static let REQUEST_FOR_CONFIRMATION_DIALOG = 38
    static let RESPONSE_FOR_CONFIRMATION_DIALOG = 39

    static let REQUEST_FOR_CDISPLAYGETPASSWORD_ACTIVITY = 40
    static let RESPONSE_FOR_CDISPLAYGETPASSWORD_ACTIVITY = 41

    static let REQUEST_FOR_CASCADING_LIST_ACTIVITY = 44
    static let RESPONSE_FOR_CASCADING_LIST_ACTIVITY = 45

    static let REQUEST_FOR_CDISPLAY_MULTI_DATA_ENTRY_ACTIVITY = 46
    static let RESPONSE_FOR_CDISPLAY_MULTI_DATA_ENTRY_ACTIVITY = 47
    static let REQUEST_FOR_PRINT_INTEGRATED_SLIP = 48

    static let RESPONSE_FOR_PRINT_INTEGRATED_SLIP = 49
    static let RESPONSE_FOR_UPI_BHARAT_QR_TXN = 50

    static let REQUEST_FOR_HOME_PAGE_ACTIVITY = 51
    static let RESPONSE_FOR_HOME_PAGE_ACTIVITY = 52
}
