//
//  StringConstant.swift
//  ePOS
//
//  Created by Vishal Rathore on 06/11/20.
//  Copyright © 2020 Pinelabs. All rights reserved.
//

import Foundation

enum StringConstant {

    static let C_LISTFILE_NAME = "ListFileActivity"
    static let NO = "no"
    static let ACTIVATE = "Activate"
    static let SETTLE_BATCH = "Settle Batch"
    static let SET_CONNECTION = "Set Connection"
    static let TEST_CONNECTION = "Test Connection"
    static let DISPLAY_PARAMS = "Display Params"
    static let LOGOUT = "Logout"
    static let INITIALIZE = "Initialize"
    static let IS_EMV = "IS_EMV"
    static let OTHER_SETTINGS = "Other Settings"
    static let MAXLEN = "MAXLEN"
    static let TITLE = "TITLE"
    static let AULT_VALUE_MAXLEN = 16
    static let ON_CREATE = "onCreate"
    static let DATA_ENTRY_TITLE = "Enter Details"
    static let MENU_TITLE = "Menu"
    static let SECRET_PIN_TITLE = "Enter PIN"
    static let LIST_OF_APP_LABLE = "LIST_OF_APP_LABLE"
    static let CLIENT_ID_TEXT = "Client ID"
    static let HARDWARE_ID = "Hardware ID"
    static let FULL_SERIAL_NUMBER = "Full Serial Number"
    static let BATCH_ID_TEXT = "Batch ID"
    static let MAX_BATCH_SIZE_TEXT = "Max Batch Size"
    static let TOTAL_TRANSACTIONS_TEXT = "Total Transactions"
    static let PARAM_DOWNLOAD_DATE_TEXT = "Param Download Date"
    static let PVM_VERSION_TEXT = "PVM Version"
    static let APP_VERSION_TEXT = "Application Version"
    static let TRACE_LOGGING_LEVEL_TEXT = "Trace Logging Level"
    static let ENABLE_TEXT = "Enable"
    static let DISABLE_TEXT = "Disable"
    static let AUTOSETTLE_STATE_TEXT = "Auto Settle State"
    static let AUTOSETTLE_START_TIME_TEXT = "Auto Settle Start Time"
    static let AUTOSETTLE_FREQ_TEXT = "Auto Settle Frequency"
    static let MERCHANT_CATEGORY_CODE_TEXT = "Merchant Category Code"
    static let IGNORE_PARITY_ERROR_TEXT = "Ignore Parity Error"
    static let AMEX_PARAM_TEXT = "AMEX Param"
    static let VISA_PARAM_TEXT = "VISA Param"
    static let MAESTRO_PARAM_TEXT = "Maestro Param"
    static let MASTER_PARAM_TEXT = "Master Param"
    static let FONT_FILE_LIST_TEXT = "Font File List"
    static let PREMIUM_MAX_RETRY_TEXT = "Premium Service Maximum Retry Count"
    static let PREMIUM_RETRY_FREQ_TEXT = "Premium Service Retry Frequency"
    static let PREMIUM_START_TIME_TEXT = "Premium Service Start Time"
    static let PREMIUM_RETRY_INTERVAL_SEC_TEXT = "Premium Service Retry Interval in Second"
    static let PREMIUM_SERVICE_STATE_TEXT = "Premium Service State"
    static let AMEX_EMV_DE55_HEX_TAG_TEXT = "AMEX EMV DE55 Hex Tag"
    static let ALWAYS_ON_RETRY_INTV_SEC_TEXT = "Always On Retry Interval in Seconds"
    static let AUTOGPRS_STATE_TEXT = "Auto GPRS State"
    static let ALWAYS_ON_TCP_TEXT = "Always on TCP"
    static let ALWAYS_ON_PPP_TEXT = "Always on PPP"
    static let AUTOREV_MAX_RETRY_TEXT = "Auto Reversal Maximum Retry Count"
    static let AUTOREV_RETRY_INTV_SEC_TEXT = "Auto Reversal Retry Interval in Seconds"
    static let AUTOREV_FIST_RETRY_INTV_SEC_TEXT = "Auto Reversal First Retry Interval in Seconds"
    static let AUTOREVERSAL_STATE_TEXT = "Auto Reversal State"
    static let IGNORE_TXN_AMOUNT_TAG_TEXT = "Ignore Transaction Amount Tag"
    static let PIN_BYPASS_SC6_TEXT = "PIN Bypass SC6"
    static let PIN_REQUIRED_SC6_TEXT = "PIN Required SC6"
    static let HOTKEY_TIMEOUT_SEC_TEXT = "Hot Key Timeout in Seconds"
    static let DISPLAY_MESSAGE_TIMEOUT_SEC_TEXT = "Display Message Timeout in Seconds"
    static let DISPLAY_MENU_TIMEOUT_SEC_TEXT = "Display Menu Timeout in Seconds"
    static let MAX_PIN_LENGTH_TEXT = "Maximum PIN Length"
    static let MIN_PIN_LENGTH_TEXT = "Minimum PIN Length"
    static let PIN_INTERCHAR_TIMEOUT_SEC_TEXT = "PIN Inter Char Timeout in Seconds"
    static let PIN_FIRST_CHAR_TIMEOUT_SEC_TEXT = "PIN First Char Timeout in Seconds"
    static let EMV_CHIP_MAX_RETRY_TEXT = "EMV Chip Maximum Retry Count"
    static let SECONDARY_IP_MAX_RETRY_TEXT = "Secondary IP Maximum Retry Count"
    static let AUTOSETTLE_RETRY_INTV_SEC_TEXT = "Auto Settle Retry Interval in Seconds"
    static let AUTOSETTLE_MAX_RETRY_TEXT = "Auto Settle Maximum Retry Count"
    static let CRIS_ENABLED_TEXT = "CRIS Enabled"
    static let LOGSHIPPING_ENABLED_TEXT = "Log Shipping"
    static let LOG_ENABLE = "Log Enable"
    static let IS_PASSWORD_NEEDED_FOR_SPECIFIC_TXNS = "Password Needed for Specific Transactions"
    static let IS_PASSWORD_REQUIRED_SETTLEMENT = "Password Required Settlement"
    static let DISPMSG_TEXT = "DISPMSG"
    static let MAX_LEN_TEXT = "MAXlEN"
    static let MIN_LEN_TEXT = "MINlEN"
    static let ACTIVITY_TIME_OUT = "TIMEOUT"
    static let LOG_UPLOAD_FREQUENCY = "Log Upload Frequency"
    static let LOG_UPLOAD_FAILURE_RETRY_COUNT = "Log Upload Failure Retry Count"
    static let LOG_UPLOAD_FAILURE_RETRY_INTERVAL_IN_SEC = "Log Upload Failure Retry Interval in Seconds"
    static let LOG_UPLOAD_START_TIME = "Log Upload Start Time"
    static let Content_Server_Enabled = "Content Server"
    static let Content_Server_Download_Url = "Content Server Download Url"
    static let Content_Server_Upload_Url = "Content Server Upload Url"
    static let Content_Server_Download_Apk_Url = "Content Server Download Apk Url"
    static let Content_Server_Connection_Time_Out = "Content Server Connection Timeout"
    static let Content_Server_Socket_Time_Out = "Content Server Socket Timeout"
    static let SFTP_HOST_NAME = "SFTP Host Name"
    static let SFTP_USER_NAME = "SFTP User Name"
    static let SFTP_PORT = "SFTP PORT"
    static let LOG_SHIPMENT_RETENTIONDAY = "Log Shipment Retention Days"
    static let LOG_BLACKLIST_START_TIME = "Log BlackList Start Time"
    static let LOG_BLACKLIST_END_TIME = "Log BlackList End Time"
    static let LOG_SHIPPING_DIRECTORY_PATH = "Log Shipping Direcetory path"
    static let LOG_SHIPMENT_LEVEL = "Log Shipment Level"
    static let LOG_SHIPMENT_RETEMTION_SIZE_INMB = "Log Shipment Retention Size In MB"
    static let MAX_LOG_FILE_SIZE = "Max Log File Size"
    static let MAX_LOG_FILE_COUNT_OF_A_DAY = "Max Log File Count Of A Day"
    
    static let LOG_SHIPPING_FAIL = "Log Shipping Failed"
    static let INTENT_HOST_ID = "iHostID"
    static let INTENT_CONNECTION_TYPE = "connectionType"
    
    static let ACTIONBAR_TITLE_COMMUNICATION_SETUP = "Communication Setup"
    static let TRUE_TEXT = "true"
    static let FALSE_TEXT = "false"
    static let SET_CONNECTION_TITLE = "Set Connection"
    static let TITLE_TEST_CONNECTION = "Test Connection"
    static let NUMERIC_ENTRY = "NUMERIC_ENTRY"
    static let ALPHANUMERIC_ENTRY = "ALPHANUMERIC_ENTRY"
    static let TIMEOUT = "timeout"
    static let BETWEEN_PIN_KEY_TIMEOUT = "betweenPinKeyTimeout"
    static let PIN_LIMIT = "pinLimit"
    static let ON_EXECUTED = "onExecuted"
    static let BACK_PRESSED = "Back pressed"
    
    static let PRINTDATA_TAG = "printdata"
    static let PRINT_IMAGEDATA_TAG = "printdataimage"
    static let PRINT_QRDATA_TAG = "printdataqr"
    static let PRINT_BARCODEDATA_TAG = "printdatabarcode"
    static let MSG_CALL = "call:"
    static let FROM = "from"
    static let SETTLE = "settle"
    static let SALE = "sale"
    static let ENTER_PASSWORD = "Enter Password"
    static let initialization_fail = "Hey, seems like it is taking longer than usual!\nDon't worry, we are trying to solve this.\nIf you are seeing this message for more than 5 minutes, please press the Call Support button, and talk to our Priority Support team."

    
    static let INT_MIN_DEFAULT_VALUE = 3
    static let INT_MAX_DEFAULT_VALUE = 9
    static let HOST_TLV_TAG_CSV = 0x1112
    static let DEFAULT_DECIMAL_POINT = 2
    static let RESULT_CODE_MERCHANT_PWD_ACTIVITY = 2
}
